@description('Name of the Azure Managed Grafana instance.')
param name string

@description('Azure region.')
param location string

@description('Resource tags.')
param tags object = {}

// Managed Grafana with a system-assigned identity and the Azure MCP endpoint.
// The endpoint is public but secured by Entra ID authentication + Grafana RBAC;
// API keys and anonymous access are disabled. This is what lets the Microsoft-
// managed SRE Agent reach the MCP endpoint.
// No Azure data-source RBAC is granted here: bring your own data sources
// (e.g. Prometheus/Loki/Tempo restored from backup) and configure their auth.
resource grafana 'Microsoft.Dashboard/grafana@2023-09-01' = {
  name: name
  location: location
  tags: tags
  sku: {
    name: 'Standard'
  }
  identity: {
    type: 'SystemAssigned'
  }
  properties: {
    apiKey: 'Disabled'
    publicNetworkAccess: 'Enabled'
    autoGeneratedDomainNameLabelScope: 'TenantReuse'
    deterministicOutboundIP: 'Disabled'
    zoneRedundancy: 'Disabled'
  }
}

output resourceId string = grafana.id
output name string = grafana.name
output endpoint string = grafana.properties.endpoint
output systemAssignedPrincipalId string = grafana.identity.principalId
